"""empty message

Revision ID: 39fc2ac7af6b
Revises: dad27fe018a9
Create Date: 2022-10-12 18:11:09.060085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39fc2ac7af6b'
down_revision = 'dad27fe018a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritecharacters', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('favoritecharacters', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritecharacters', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('favoriteplanets', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('favoriteplanets', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoriteplanets', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favoriteplanets', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoriteplanets', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favoriteplanets', 'id')
    op.alter_column('favoritecharacters', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritecharacters', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favoritecharacters', 'id')
    # ### end Alembic commands ###
